CREATE DATABASE IF NOT EXISTS demo;

CREATE TABLE IF NOT EXISTS demo.users (
    id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    status ENUM ('UNVERIFIED', 'VERIFIED', 'SUSPENDED') NOT NULL DEFAULT 'UNVERIFIED',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    password VARCHAR(128) NOT NULL,
    PRIMARY KEY (id), UNIQUE (email)
);
